config/routes.rb
Rails.application.routes.draw do
  get "profiles/show"
  resources :links
  resources :images, only: [:show, :update, :destroy]
  resources :news_feeds
  devise_for :users

  namespace :api, format: 'json' do
    namespace :v1 do
      resources :sub_collections, only: [:index, :show, :create, :destroy]

      resources :likes, only: [:create, :index, :show] do
        collection do
          delete '', to: 'likes#destroy'
        end
      end

      resources :effects, only: [:index, :show, :destroy] do
        collection do
          get 'my', to: 'effects#my_effects'
          get 'feed', to: 'effects#feed'
        end
        resources :comments, only: [:index, :show, :create, :update, :destroy]
      end
      resources :users, only: [:index, :show] do
        collection do
          get 'me', to: 'users#me'
        end
      end
      
      resources :profiles, only: [:show] do
        collection do
          get 'me', to: 'profiles#me'
          patch '', to: 'profiles#update'
          delete '', to: 'profiles#destroy'
        end
      end
      
      resources :favorites, only: [:create] do
        delete ":effect_id", to: "favorites#destroy", on: :collection
      end      
      resources :collections, only: [:index, :show, :create, :destroy] do
        collection do
          get 'my', to: 'collections#my_collections'
        end
        member do
          patch 'update_status'
          post 'effects/:effect_id', to: 'collections#add_effect', as: 'add_effect'
          delete 'effects/:effect_id', to: 'collections#remove_effect', as: 'remove_effect'
          post 'effects/bulk_add', to: 'collections#bulk_add_effects', as: 'bulk_add_effects'
          post 'links', to: 'collections#add_link', as: 'add_link'
          patch 'links/:link_id', to: 'collections#update_link', as: 'update_link'
          delete 'links/:link_id', to: 'collections#remove_link', as: 'remove_link'
          post 'images', to: 'collections#add_image', as: 'add_image'
          patch 'images/:image_id', to: 'collections#update_image', as: 'update_image'
          delete 'images/:image_id', to: 'collections#remove_image', as: 'remove_image'
        end
        resources :collection_effects, only: [:create], path: 'effects'
      end

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end

  resources :profiles, only: [:show, :edit, :update]

  # get 'profiles/:id', to: 'profiles#show', as: 'profile'

  # Custom route for deleting effects from collections
  delete 'remove_effect_from_collection/:collection_id/:effect_id', to: 'collection_effects#destroy_by_ids', as: :remove_effect_from_collection

  resources :sub_collections
  resources :collection_effects
  resources :collections, path: 'collection' do
    resources :links, only: [:index]
    resources :images
    collection do
      get 'tagged/:tag', to: 'collections#by_tag', as: :tagged
      get 'search', to: 'collections#search'
    end
    member do
      post 'subscribe'
      delete 'unsubscribe'
      post 'effects/bulk_add', to: 'collections#bulk_add_effects'
      post 'effects/bulk_update', to: 'collections#bulk_update_effects'
      post 'add_link', to: 'collections#add_link'
    end
  end

  get 'effects/categorie/:category', to: 'effects#categorie', as: :effects_categorie

  # Trending routes
  get 'effects/trending', to: 'effects#trending', as: :trending_effects
  get 'collections/trending', to: 'collections#trending', as: :trending_collections
  get 'collections/similar', to: 'collections#similar', as: :similar_collections
  get 'effects/similar', to: 'effects#similar', as: :similar_effects

  resources :subscriptions, only: [:create]
  resources :favorites do
    collection do
      post 'add_link', to: 'favorites#add_link'
      post 'add_image', to: 'favorites#add_image'
      delete 'links/:link_id', to: 'favorites#remove_link', as: 'remove_link'
      patch 'links/:link_id', to: 'favorites#update_link', as: 'update_link'
      delete 'images/:image_id', to: 'favorites#remove_image', as: 'remove_image'
      patch 'images/:image_id', to: 'favorites#update_image', as: 'update_image'
      get 'links/:link_id', to: 'favorites#show_link', as: 'show_link'
      get 'images/:image_id', to: 'favorites#show_image', as: 'show_image'
    end
  end
  
  # Bulk add effects to collection route
  post 'collections/:id/effects/bulk_add', to: 'collections#bulk_add_effects', as: :bulk_add_effects_to_collection
  
  resources :effects do
    collection do
      get 'my', to: 'effects#my', as: :my
      get 'feed', to: 'effects#feed', as: :feed
      post 'save_preferences', to: 'effects#save_preferences'
    end
    member do
      patch :approve
      patch :reject
      patch :resubmit
    end
    collection do
      get 'categories', to: 'effects#categories'
      get 'tagged/:tag', to: 'effects#by_tag', as: :tagged
    end
    resources :comments do
      resources :ratings, only: [:create]
    end
  end

  # OG Images routes
  get 'og_images/effect/:id', to: 'og_images#effect', as: :og_image_effect
  get 'og_images/collection/:id', to: 'og_images#collection', as: :og_image_collection
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get 'about', to: 'welcome#about', as: 'welcome_about'
  get 'search', to: 'welcome#search', as: 'search_results'
  # get 'about', to: 'welcome#about'
  # get 'allTasks', to: 'welcome#allTasks'
  # get 'searchTasks', to: 'welcome#searchTasks'
  # get 'howToPlay', to: 'welcome#howToPlay'
  # get 'answersGallery', to: 'tasks#answersGallery'

  # Error pages
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all

  # Static files with CORS headers
  get '/uploads/*path', to: 'uploads#show', constraints: { path: /.*/ }

  # Defines the root path route ("/")
  root "welcome#index"
  
  # Catch all unmatched routes (must be last)
  match '*path', to: 'errors#not_found', via: :all
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :ratings, as: :ratingable
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: %i[ show edit update destroy ]

  # GET /assets or /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1 or /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets or /assets.json
  def create
    @asset = Asset.new(asset_params)
    @question.user_id = 1

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: "Asset was successfully created." }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1 or /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: "Asset was successfully updated." }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1 or /assets/1.json
  def destroy
    @asset.destroy!

    respond_to do |format|
      format.html { redirect_to assets_path, status: :see_other, notice: "Asset was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asset_params
      params.require(:asset).permit(:name, :img, :description, :devices, :manual, :link_to, :is_secure, :speed, :user_id)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_asset.html.erb
<div id="<%= dom_id asset %>">
  <p>
    <strong>Name:</strong>
    <%= asset.name %>
  </p>

  <p>
    <strong>Img:</strong>
    <%= asset.img %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= asset.description %>
  </p>

  <p>
    <strong>Devices:</strong>
    <%= asset.devices %>
  </p>

  <p>
    <strong>Manual:</strong>
    <%= asset.manual %>
  </p>

  <p>
    <strong>Link to:</strong>
    <%= asset.link_to %>
  </p>

  <p>
    <strong>Is secure:</strong>
    <%= asset.is_secure %>
  </p>

  <p>
    <strong>User:</strong>
    <%= asset.user_id %>
  </p>

</div>

app/views/assets/_form.html.erb
<%= form_with(model: asset) do |form| %>
  <% if asset.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
        <% asset.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :devices, style: "display: block" %>
    <%= form.text_area :devices %>
  </div>

  <div>
    <%= form.label :manual, style: "display: block" %>
    <%= form.text_area :manual %>
  </div>

  <div>
    <%= form.label :link_to, style: "display: block" %>
    <%= form.text_field :link_to %>
  </div>

  <div>
    <%= form.label :speed, style: "display: block" %>
    <%= form.text_field :speed %>
  </div>

  <div>
    <%= form.label :is_secure, style: "display: block" %>
    <%= form.check_box :is_secure %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<% content_for :title, "Editing asset" %>

<h1>Editing asset</h1>

<%= render "form", asset: @asset %>

<br>

<div>
  <%= link_to "Show this asset", @asset %> |
  <%= link_to "Back to assets", assets_path %>
</div>

app/views/assets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Assets" %>

<h1>Routes</h1>

<ul>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Questions', questions_path %></li>
  <li><%= link_to 'Favorites', favorites_path %></li>
  <li><%= link_to 'Ratings', ratings_path %></li>
  <li><%= link_to 'Collections', collections_path %></li>
  <li><%= link_to 'Assets', assets_path %></li>
</ul>

<h1>Assets</h1>

<div id="assets">
  <% @assets.each do |asset| %>
    <%= render asset %>
    <p>
      <%= link_to "Show this asset", asset %>
    </p>
  <% end %>
</div>

<%= link_to "New asset", new_asset_path %>

app/views/assets/new.html.erb
<% content_for :title, "New asset" %>

<h1>New asset</h1>

<%= render "form", asset: @asset %>

<br>

<div>
  <%= link_to "Back to assets", assets_path %>
</div>

app/views/assets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @asset %>

<div>
  <%= link_to "Edit this asset", edit_asset_path(@asset) %> |
  <%= link_to "Back to assets", assets_path %>

  <%= button_to "Destroy this asset", @asset, method: :delete %>
</div>